on:
  push:
    branches:
      - main

jobs:
  run-stuff:
    name: Run stuff
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 30 seconds
        run: sleep 30

  hello-world:
    name: Hello World
    runs-on: ubuntu-latest
    needs: run-stuff
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: |
          python main.py
