on:
  push:
    branches:
      - main

jobs:
  run-stuff:
    name: Run stuff
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 60 seconds
        run: sleep 60

  hello-world:
    name: Hello World
    runs-on: ubuntu-latest
    needs: run-stuff
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: |
          python main.py

  wait-long-time:
    name: Long time
    if: ${{ github.ref_name == 'x' }}
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 90 seconds
        run: sleep 90
  # test5:
  #   concurrency:
  #     group: checkout-repo
  #     cancel-in-progress: false
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: sleep 20
  #     - name: Run tests
  #       run: echo ${{ needs.test3.outputs.thishas-hyphen }}
  #     - name: Run tests
  #       run: echo ${{ needs.test3.outputs.thishas-hyphen2 }}
  test4:
    concurrency:
      group: checkout-repo
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - run: sleep 20
      - name: Run tests
        run: echo ${{ needs.test3.outputs.thishas-hyphen }}
      - name: Run tests
        run: echo ${{ needs.test3.outputs.thishas-hyphen2 }}
  test9:
    name: "install go sqlcmd"
    runs-on: ubuntu-latest
    steps:
      # - name: Install go
      #   uses: actions/setup-go@v5
      #   with:
      #     go-version: 1.23
      - name: Install sqlcmd
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update
          sudo apt-get install mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
          source ~/.bashrc
          source ~/.bash_profile
          sqlcmd -?
      - name: Check sqlcmd
        run: |
          source ~/.bashrc
          source ~/.bash_profile
          sqlcmd -?
  test1:
    name: "install go sqlcmd"
    runs-on: ubuntu-latest
    steps:
      - name: Install sqlcmd
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update
          sudo apt-get install mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> $GITHUB_ENV
          sqlcmd -?

      - name: Check sqlcmd
        env:
          PATH: ${{ env.PATH }}:/opt/mssql-tools/bin
        run: |
          sqlcmd -?
