on:
  push:
    branches:
      - main

env:
  MY_ENV_VAR: "secret"

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: echo "Running tests on ${{ matrix.os }}"
      - name: Test this runs independent of the matrix
        run: echo "this"
      - run: echo ${{ env.MY_ENV_VAR }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          python main.py
  test3:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    concurrency: checkout-repo
    outputs:
      thishas-hyphen: ${{ steps.run.outputs.test-output }}
      thishas-hyphen2: ${{ steps.run2.outputs.test-output }}
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        id: run
        run: echo "test-output=helloworld" >> $GITHUB_OUTPUT
      - name: Run tests
        id: run2
        run: echo "test-output=foobar" >> $GITHUB_OUTPUT

  test4:
    needs: test3
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo ${{ needs.test3.outputs.thishas-hyphen }}
      - name: Run tests
        run: echo ${{ needs.test3.outputs.thishas-hyphen2 }}
