on:
  push:
    branches:
      - main

env:
  MY_ENV_VAR: "secret"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: echo "Running tests on ${{ matrix.os }}"
      - name: Test this runs independent of the matrix
        run: echo "this"
      - run: echo ${{ env.MY_ENV_VAR }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.MY_ENV_VAR }}

  test3:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    concurrency: checkout-repo
    outputs:
      thishas-hyphen: ${{ steps.run.outputs.test-output }}

    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        id: run
        run: echo "test-output=helloworld" >> $GITHUB_OUTPUT

  test4:
    needs: test3
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "test-output=helloworld" >> $GITHUB_OUTPUT
