on:
  push:
    branches:
      - main

env:
  MY_ENV_VAR: "secret"
  TEST: ${{ "hello" == "world" }}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    outputs:
      test: ${{ github.ref_name == "main" }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: echo "Running tests on ${{ matrix.os }}"
      - name: Test this runs independent of the matrix
        run: echo "this"

  test2:
    needs: test
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    concurrency: checkout-repo
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: echo "${{ needs.test.outputs.test }}"
  test3:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    concurrency: checkout-repo
    steps:
      - uses: actions/checkout@v4
