on:
  push:
    branches:
      - main

jobs:
  wait:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          running-workflow-name: "Wait for tests to succeed"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Yay
        run: echo "Hello World succeeded!"
